package com.onlineshoppingmall.dataobject;

public class PasswdDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passwd.id
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passwd.encrpt_passwd
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    private String encrptPasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column passwd.user_id
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passwd.id
     *
     * @return the value of passwd.id
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passwd.id
     *
     * @param id the value for passwd.id
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passwd.encrpt_passwd
     *
     * @return the value of passwd.encrpt_passwd
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public String getEncrptPasswd() {
        return encrptPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passwd.encrpt_passwd
     *
     * @param encrptPasswd the value for passwd.encrpt_passwd
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public void setEncrptPasswd(String encrptPasswd) {
        this.encrptPasswd = encrptPasswd == null ? null : encrptPasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column passwd.user_id
     *
     * @return the value of passwd.user_id
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column passwd.user_id
     *
     * @param userId the value for passwd.user_id
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}