package com.onlineshoppingmall.dataobject;

public class UserDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.name
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    private Byte gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.age
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phonenum
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    private String phonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.means
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    private String means;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id_three
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    private String idThree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.name
     *
     * @return the value of user_info.name
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.name
     *
     * @param name the value for user_info.name
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.age
     *
     * @return the value of user_info.age
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.age
     *
     * @param age the value for user_info.age
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phonenum
     *
     * @return the value of user_info.phonenum
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phonenum
     *
     * @param phonenum the value for user_info.phonenum
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.means
     *
     * @return the value of user_info.means
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public String getMeans() {
        return means;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.means
     *
     * @param means the value for user_info.means
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public void setMeans(String means) {
        this.means = means == null ? null : means.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id_three
     *
     * @return the value of user_info.id_three
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public String getIdThree() {
        return idThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id_three
     *
     * @param idThree the value for user_info.id_three
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    public void setIdThree(String idThree) {
        this.idThree = idThree == null ? null : idThree.trim();
    }
}