package com.onlineshoppingmall.dao;

import com.onlineshoppingmall.dataobject.PasswdDo;

public interface PasswdDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passwd
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passwd
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    int insert(PasswdDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passwd
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    int insertSelective(PasswdDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passwd
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    PasswdDo selectByPrimaryKey(Integer id);
    PasswdDo selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passwd
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    int updateByPrimaryKeySelective(PasswdDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table passwd
     *
     * @mbg.generated Wed Aug 14 15:00:11 CST 2019
     */
    int updateByPrimaryKey(PasswdDo record);
}